CREATE TABLE "brands" (
  "brand_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "brand_name" varchar(50) NOT NULL DEFAULT 'brand name missing'
);

CREATE TABLE "categories" (
  "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "category_name" varchar(50) NOT NULL DEFAULT 'category name missing',
  "type" varchar(30)
);

CREATE TABLE "items" (
  "description" varchar(300) DEFAULT 'description missing',
  "image_url" varchar(2048) NOT NULL DEFAULT 'image missing',
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "item_name" varchar(50) NOT NULL DEFAULT 'item name missing',
  "item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL
);

CREATE TABLE "item_brand" (
  "brand_id" integer NOT NULL REFERENCES brands ON DELETE RESTRICT,
  "item_id" integer NOT NULL REFERENCES items ON DELETE CASCADE,
  PRIMARY KEY ("item_id", "brand_id")
);

CREATE TABLE "item_price" (
  "item_price_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "item_id" integer NOT NULL REFERENCES items ON DELETE CASCADE,
  "price" numeric(4,2) NOT NULL DEFAULT 0 CHECK (price > 0),
  PRIMARY KEY ("item_id", "price")
);

CREATE TABLE "item_category" (
  "item_id" integer NOT NULL REFERENCES items ON DELETE CASCADE,
  "category_id" integer NOT NULL REFERENCES categories ON DELETE CASCADE,
  PRIMARY KEY ("item_id", "category_id")
);

CREATE TABLE "inventory" (
  "item_price_id" integer PRIMARY KEY NOT NULL REFERENCES item_price ON DELETE CASCADE,
  "date_updated" timestamptz NOT NULL DEFAULT (now()),
  "count" integer NOT NULL DEFAULT 0
);

